apiVersion: apps/v1
kind: StatefulSet
metadata: 
       name: sset
       labels:
            app: sset
spec: 
    replicas: 3  #how many replica's you want to create on the basis of template
    template:
      metadata:  #like a tag
         name: sset
         labels: 
            app: sset
      spec:
        containers:
            - name: mypod-ss
              image: mysql:latest
              resources: 
                  requests:
                    cpu: "50m"
                    memory: "90Mi"        
              ports:  
                - name: dbport
                  containerPort: 3306
                  protocol: TCP
              env:
                 - name: MYSQL_ROOT_PASSWORD
                   value: "1234"
    selector:
        matchLabels:
          app: sset