apiVersion: apps/v1
kind: Deployment
metadata: 
        name: studentapp
        labels:
            app: studentapp
spec:
    replicas: 8
    strategy: 
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 2   # Maximum number of pods that can be created over the desired replicas
          maxUnavailable: 2  # Maximum number of pods that can be unavailable during the update 
    template:
          metadata: 
                name: studentapp
                labels:
                      app: studentapp
          spec:
              containers:
                  - name: http
                    image: pallavi1104/student
                    resources: 
                      requests:
                          cpu: "50m"
                          memory: "90Mi" 
                    ports:
                        - name: http
                          containerPort: 80
                          protocol: TCP      
    selector:
        matchLabels:
            app: studentapp


---
apiVersion: v1 
kind: Service
metadata:
    name: mystudentapp
spec:
  type: LoadBalancer
  selector: 
      app: studentapp
  ports:
    - port: 80
      targetPort: 8080   # Correct field name
      protocol: TCP
      name: studentapp
