apiVersion: apps/v1
kind: Deployment
metadata: 
        name: todoapp
        labels:
            app: todoapp
spec:
    replicas: 8
    strategy: 
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 2   # Maximum number of pods that can be created over the desired replicas
          maxUnavailable: 2  # Maximum number of pods that can be unavailable during the update 
    template:
          metadata: 
                name: todoapp
                labels:
                      app: todoapp
          spec:
              containers:
                  - name: http
                    image: pallavi1104/todo
                    resources: 
                      requests:
                          cpu: "50m"
                          memory: "90Mi" 
                    ports:
                        - name: http
                          containerPort: 80
                          protocol: TCP      
    selector:
        matchLabels:
            app: todoapp


---
apiVersion: v1 
kind: Service
metadata:
    name: mytodo
spec:
  type: LoadBalancer
  selector: 
      app: todoapp
  ports:
    - port: 80
      targetPort: 80   # Correct field name
      protocol: TCP
      name: todoapp
