apiVersion: apps/v1
kind: Deployment
metadata: 
        name: todoapp
        labels:
            app: todoapp
spec:
    replicas: 15
    strategy: 
        type: RollingUpdate
        rollingUpdate:
          maxSurge: 3   # Maximum number of pods that can be created over the desired replicas
          maxUnavailable: 3  # Maximum number of pods that can be unavailable during the update 
    template:
          metadata: 
                name: todoapp
                labels:
                      app: todoapp
          spec:
              containers:
                  - name: http
                    image: tomcat
                    resources: 
                      requests:
                          cpu: "50m"
                          memory: "90Mi" 
                    ports:
                        - name: http
                          containerPort: 80
                          protocol: TCP      
    selector:
        matchLabels:
            app: todoapp


---
apiVersion: v1 
kind: service
metadata:
        name: mytodo
spec:
 type: LoadBalancer
 selector: todoapp
 ports:
   - port: 80
     targetport: 80
     protocol: TCP
     name: todoapp         
